### ISSUE TITLE
generate_release_package.pyが正常に動作しない

### ISSUE THREAD

**Issue by rumichi2210** [effekseer/EffekseerForDXLib#3]
generate_release_package.py実行時に
FileNotFoundError: [Errno 2] No such file or directory: '../Effekseer/EffekseerRuntime_DXLib/Compiled/include/Effekseer.h'
とエラーが発生します。
DXライブラリ用のEffekseer.hはどのように用意すればいいでしょうか？
宜しくお願いいたします。

**Comment by durswd** [comment]
この部分も、copy_packageの最新版に合わせる必要がありそうです。
https://github.com/effekseer/EffekseerForDXLib/blob/master/copy_package.py#L20

**Comment by durswd** [comment]
https://github.com/effekseer/EffekseerForDXLib/commit/d071292cefaceddee59c57918134df9fd62d489d

これで直しました

**Comment by durswd** [comment]
Readmeも更新しました。

**Comment by rumichi2210** [comment]
正しくパッケージ化されるようになりました。
お手数おかけしました。
